### ISSUE TITLE
Target temperature empty sends TARGER=NaN and causes the heater to heat to infinity

### ISSUE THREAD

**Issue by pszeder** [cadriel/fluidd#108]
How to reproduce: 
- Delete any number from the Target temperature of the extruder
- Press enter

Result: 
- The contents of the Thermals will stop updating. (Maybe other things also stop updating, haven't checked). After entering a valid number it will start updating again. (Mainsail also stops updating the temperatures at the same time)
- Console says: $ SET_HEATER_TEMPERATURE HEATER=extruder TARGET=NaN
- Heater heats up to 270 degrees (my max temp) then printer Klipper shuts off. 

There could be some improvements that can be made in the UI, but my feeling is also that this is a Moonraker/Klipper problem as well, as NaN should not heat to infinity and beyond. I'll not post it there until I get a response here. 

I'm not too much into Klipper development (yet?), but if I get some encouragement I may look into it :)

For the UI, I would prefer to have a button next to each heater to disable them and I would parse 0 or NaN in the input as disabled.

**Comment by cadriel** [comment]
![Screen Shot 2021-01-20 at 10 43 38 AM](https://user-images.githubusercontent.com/205520/105206794-5f355d00-5b0c-11eb-9b0d-39bcb413e681.png)

I can't actually do what you suggest, but It's maybe because of a difference in `printer.cfg`. Do you have a `min_temp` and `max_temp` set for your extruder?

An upcoming change in klipper will likely fix this. Currently I don't get defaults for some values, but I need to know how you're reproducing in order to diagnose.

**Comment by cadriel** [comment]
https://github.com/KevinOConnor/klipper/issues/3811

I've created an issue in Klipper for this also.

**Comment by cadriel** [comment]
I'll also be adding a num check here to avoid this issue irrelevant of min / max's. Thanks for the report!

**Comment by pszeder** [comment]
Thank you!

I had min_temp set as 0. After changing it to 1 and doing the same steps I've got invalid/red as you shown in your screenshot. This feels like that input validation is not applied in this case.

**Comment by cadriel** [comment]
It wasn't checking validation when hitting return in this case.

Now resolved tho..
