### ISSUE TITLE
Docker images don't have release tags

### ISSUE THREAD

**Issue by dimalo** [cadriel/fluidd#115]
[https://hub.docker.com/r/cadriel/fluidd/tags](https://hub.docker.com/r/cadriel/fluidd/tags)

just showing latest only, even on building only for releases.

perhaps triggering by the release workflow being completed doesn't pass tags compared to trigger on push?

**Comment by cadriel** [comment]
Possibly, the problem is that the docker publish can't happen until after the release, otherwise it'll pick up the wrong release artifact.

It really shouldn't be otherwise built / released outside of an actual Fluidd release.

I am aware of the issue - but haven't had time to investigate a solution yet.

**Comment by cadriel** [comment]
This should now be resolved

**Comment by dimalo** [comment]
confirming - great job!
