### ISSUE TITLE
RFE: make delta_calibrate mode=manual less tedius by adding some UI features.

### ISSUE THREAD

**Issue by deltamelter** [cadriel/fluidd#176]
delta calibration is really effective and relatively simple in principal with Klipper, but in practice it becomes a totally tedius chore.
Why is it tedius? Well it 's mostly done with console commands and for one thing fluidd only seems to buffer the last 4 -5 commands so you can't even use up arrow to quickly reselect from previous step.

The process itself goes like this:
type "G28 z0" to home
type "delta_calibrate mode=manual"
printer now moves 5mm above the centre of the bed...
use the command "TESTZ z=-1"  to move the nozzle closer to the bed....
repeat with larger or smaller, positive or negative values as small as you motors/baby-stepping allow..
once you are down to the "paper test" distance from the printer, type "accept"...
on it moves to the second of 7 points...
up arrow to the "TESTZ" command you used in the previous and oh, wait, I did more than 5 commands since the once I could reuse so now I have to type again "TESTZ z=-2"  or whatever
repeat again, TESTZ after TESTZ until we're at the desired "paper_test" height.
type "accept" (because it's not in the limited command buffer (did I mention how impractically short that is?))
2 down, 5 to go.... took longer so far than writing this description...

You get the picture right?

I'll look at making some macros, but would be nicer to have simple interface to do these steps with a couple of clicks, or even wheel scrolls to adjust up and down ;D
I think this TESTZ and accept process is used for other non-delta specific functions and would benefit from simplified UI interface too...
do you support plugins or other developer mods?

**Comment by cadriel** [comment]
Z calibration has similar constraints for a lot of other types of printers. The one upside here is generally you don't have to do it too often.

We've discussed ways to improve this process, by way of having metadata that moonraker / klipper can pass through so we can present appropriate UI to make this easier. However - we'll need to wait for those discussions to flesh out a specific approach first.

In the mean time, the next release of fluidd will greatly increase the command history - and the command history gets saved between sessions, so hopefully that'll help alleviate some of these problems.

I'm going to close this for now - since it's already on the roadmap.

Developer mods come by way of Moonraker, however - I accept PR's for relevant features.

Thanks!
