### ISSUE TITLE
Track Actual Print time for job

### ISSUE THREAD

**Issue by weasel0x00** [cadriel/fluidd#195]
Would be cool to have Fluidd actually track the print time in the jobs list for a completed job, so it can be compared to the slicer estimate, and perhaps tune the slicer to estimate better.

**Comment by cadriel** [comment]
Ok;

Currently, we're squeezed for space on the dashboard's card page.

As an interim solution, i've added the actual print time to the job PAGE (versus the dashboard).

Secondarily, I'll be adding a mechanism whereby users can select what table columns to show in all locations in a future update, which then gives control to the user on what to show where.

I'll close this for now, since I believe this covers the initial requirement. :)
