### ISSUE TITLE
video for camera on firefox 87.0 stuck

### ISSUE THREAD

**Issue by sakoula** [cadriel/fluidd#220]
firefox version: 87.0
platform: macos Big Sur

Video on Firefox is stuttering and stuck after a while. On the webdeveloper it seems that it stops requesting /webcams url after some time. I include a screenshot. 

It works just fine on safari and chrome.

BTW thanks for the amazing software!

![Screenshot 2021-04-03 at 10 47 00 AM](https://user-images.githubusercontent.com/1192173/113472213-40d3d200-946a-11eb-9925-f3333451f072.png)

**Comment by cadriel** [comment]
I can't reproduce this.

I can have firefox running, with its dev tools open - and i see the requests slow after some time, but as soon as I close dev tools - the fps jumps back up to as expected rates.

I suspect in your case, it may have something to do with your wifi network, and the differences in the way firefox and other browser may handle those requests. But I can't otherwise see why there would be a difference between browsers here.

mjpgstreamer is incredibly network resource intensive - and we're looking at ways to alleviate this.

Going to close for now since I can't reliably reproduce, but I'll keep an eye out for other users having similar issues.

Thank you!
