### ISSUE TITLE
Feature Request: Power Button on top

### ISSUE THREAD

**Issue by dushyantahuja** [cadriel/fluidd#252]
Is it possible to add the power button for the printer at the header?

Preferably where the blue circle is in the image below. 
<img width="1050" alt="Screenshot 2021-04-17 at 11 12 53 PM" src="https://user-images.githubusercontent.com/6416649/115121889-b1363380-9fd2-11eb-8e46-da22caa8f588.png">

**Comment by cadriel** [comment]
There's no real way to distinguish a power button, versus powering anything else. Also, power is a moonraker plugin - so it really needs its own unique place to manage because not every user configures this the same as others.

I'd also like to keep the header as minimalist as possible.

For these reasons I think adding a button up here is not doable.

Thank you!

**Comment by dushyantahuja** [comment]
Sure - I was thinking more on the lines of - if the switch is called "printer" put it on the header. It would make things so much more convenient.

**Comment by 1ac3124** [comment]
@cadriel what do you think about power widget on dashboard like this?
<img width="604" alt="2021-04-20 21-6cikfpci01frcjo" src="https://user-images.githubusercontent.com/910648/115453366-39f9dd00-a228-11eb-8e14-be113ecc5156.png">

**Comment by cadriel** [comment]
Fluidd used to have the power widget on the dashboard in this form, but it takes up too much space for very little benefit, so was moved to the hamburger menu.
