### ISSUE TITLE
FEATURE REQUEST: Is there anyway of adding a power button?

### ISSUE THREAD

**Issue by krpepe** [cadriel/fluidd#36]
Hello,

Thank you for the wonderful interface for klipper! I absolutely love it! One question, is there any way to add a power button that would work with  https://github.com/Raabi91/powermanager. Would like to have the ability to turn on the printer from the interface.

Thank you in advance,

Kevin

**Comment by cadriel** [comment]
klipper has a power plugin, which fluidd works with already.

**Comment by krpepe** [comment]
Any possibility you could point me to what you are talking about? Apparently I am blind or stupid because I haven't been able to find a power button on the user interface.

Kevin

**Comment by cadriel** [comment]
https://github.com/Arksine/moonraker/blob/master/docs/configuration.md

That explains how to setup the power plugin in moonraker. Once you have that configured, then the buttons will show up inside Fluidd.

**Comment by krpepe** [comment]
Thank you very much! I truly appreciate the help! Have a great weekend.

Kevin

**Comment by lalek54** [comment]
Hi. 
i tried to configuré à wifi plug. 
But power.py can’t init due to lack of gpiod module in moonraker-env on fluiddpi image. 
Due to that moonraker server is shutting down. 
installing gpiod in moonraker env solve the problèm. 

And also can you tell me where should be the « power printer » button in fluidd. I don’t see it.

**Comment by lalek54** [comment]
Problème solved. Thank for your incredible work.
