### ISSUE TITLE
FR: Temperature Graph Scale Adjustment

### ISSUE THREAD

**Issue by J4CKT** [cadriel/fluidd#60]
Thank you for the awesome interface.

Would it be possible to add scale adjustment of the temperature graph to be able to show 20 / 30 / 60 / 120 minutes etc so you can see how long you have been preheating.

Would be very helpful especially for those with large printers like my 350 v2 that needs over an hour heatup for a consistent first layer.

Thanks!

**Comment by cadriel** [comment]
- X axis is directly effected by width. You lose resolution as the width of the graph is reduced, so adding further time to the scale here would adversely effect the reason the temp graph exists.
- I feel like relying on the temp graph to determine how long you've been preheating is the wrong approach.

Closing as wont fix for now because of the above reasons.

**Comment by cadriel** [comment]
For those involved, this is coming in for the next update.

You'll be able to define the length moonraker stores temperature values - and Fluidd will respect that setting in its thermals graph.
