### ISSUE TITLE
Resize Text on AppBar when on mobile

### ISSUE THREAD

**Issue by barecool** [cadriel/fluidd#61]
Thanks for all the work on this... 

this request is just a cosmetic thing:
Title text on appbar next to logo should resize to a smaller text when on mobile, to allow the whole title to be shown?
also utf font not rendering correctly (for example on the screenshot it should be a zero with a slash on it.

![Screenshot (21)](https://user-images.githubusercontent.com/2767896/103415098-4e657d00-4b46-11eb-903f-0c952e19f5b5.png)

**Comment by cadriel** [comment]
The next update reduces the font size. Please keep an eye out and let me know if this is still an issue.

The `0` with a slash in it is I believe because it's an unsupported glyph in the font face being used, which is Roboto. This font supports many languages tho, so I'm interested to know how you picked that particular 0.

For example, the following work fine;
```
∅
Ø
```
