### ISSUE TITLE
Relative asset and server path

### ISSUE THREAD

**Issue by davidsteinberger** [cadriel/fluidd#98]
I absolutely love fluidd. One thing though that would make my life easier is when the static assets and the server would use relative urls. I'm limited on the number of subdomains and would like to expose fluidd on the reverse-proxy via _some-domain/printer_.

**Comment by cadriel** [comment]
Fluidd is built and deployed to many locations. In order to support this I'd need to build with this support in mind, along with considering the url scheme..

It's not likely to happen soon.

You might want to look into the docker instead tho, you could easily reverse proxy that anywhere you'd want I believe.
